apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - mysql-k8s.yaml
  - kafka-k8s.yaml
  - zookeeper-k8s.yaml

patches:
  - path: gateway-nodeport.yaml
  - path: frontend-nodeport.yaml
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: app-config
        namespace: estate-rental
      data:
        FRONTEND_URL: "http://192.168.39.108:30417"
