apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret.yaml
  - configmap.yaml
  - auth-server-k8s.yaml
  - config-service-k8s.yaml
  - gateway-service-k8s.yaml
  - notification-service-k8s.yaml
  - property-microservice-k8s.yaml
  - public-app-k8s.yaml
  - rental-agreement-microservice-k8s.yaml
  - user-service-k8s.yaml
  - zookeeper-k8s.yaml
  - kafka-k8s.yaml
  - ml-predictive-heatmaps-k8s.yaml
  - ml-price-suggestion-k8s.yaml
  - ml-property-recommendation-k8s.yaml
  - ml-tenant-risk-scoring-k8s.yaml
